[workspace]
members = [
	"moq-transport",
	"moq-relay-ietf",
	"moq-pub",
	"moq-sub",
	"moq-api",
	"moq-clock-ietf",
	"moq-dir",
	"moq-native-ietf",
	"moq-catalog",
]
resolver = "2"

[workspace.dependencies]
web-transport = { git = "https://github.com/rimmelb/web-transport.git", branch = "relay-side-drop-implementation", package = "web-transport" }
web-transport-quinn     = { git = "https://github.com/rimmelb/web-transport.git", branch = "relay-side-drop-implementation", package = "web-transport-quinn" }
web-transport-proto     = { git = "https://github.com/rimmelb/web-transport.git", branch = "relay-side-drop-implementation", package = "web-transport-proto" }
web-transport-trait     = { git = "https://github.com/rimmelb/web-transport.git", branch = "relay-side-drop-implementation", package = "web-transport-trait" }
env_logger = "0.11"
log = { version = "0.4", features = ["std"] }

# Use debug symbols in production until things are more stable
[profile.release]
debug = true

[patch.crates-io]
quinn       = { git = "https://github.com/rimmelb/quinn.git", branch = "relay-side-drop-implementation", package = "quinn" }
quinn-proto = { git = "https://github.com/rimmelb/quinn.git", branch = "relay-side-drop-implementation", package = "quinn-proto" }

[patch."https://github.com/quinn-rs/quinn"]
quinn-proto = { git = "https://github.com/rimmelb/quinn.git", branch = "relay-side-drop-implementation", package = "quinn-proto" }
