#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "/mnt/c/Users/Rimmel Botond/Documents/bme/hatodikfelev/onlab/moq-rs"

# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to localhost by default.
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"
SCHEME="${SCHEME:-https}"

# Combine the host and name into a URL.
URL="${URL:-"$SCHEME://$ADDR"}"

cargo run --bin moq-clock-ietf -- "$URL" "$@"
