#!/bin/bash
set -euo pipefail

# Change directory to the root of the project
cd "/mnt/c/Users/Rimmel Botond/Documents/bme/hatodikfelev/onlab/moq-rs"
# Use debug logging by default
export RUST_LOG="${RUST_LOG:-debug}"

# Connect to localhost by default.
HOST="${HOST:-localhost}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"

# Use the broadcast name "bbb" by default
NAME="${NAME:-bbb}"

# Combine the host and name into a URL.
URL="${URL:-"https://$ADDR/$NAME"}"

ENABLE_DELIVERY="${ENABLE_DELIVERY:-false}"

ARGS=""

# Only add the flag if ENABLE_DELIVERY is true
if [ "$ENABLE_DELIVERY" = "true" ]; then
    ARGS="$ARGS --enable-delivery"
fi

DEADLINE_THRESHOLD_MS="${DEADLINE_THRESHOLD_MS:-50}"

# Build CLI args for moq-sub

ARGS="$ARGS --deadline-threshold-ms $DEADLINE_THRESHOLD_MS"

cargo run --bin moq-sub -- --name "$NAME" "$URL" $ARGS "$@" | ffplay -
