#!/bin/bash
set -euo pipefail

cd "/home/user/moq-rs"
export RUST_LOG="${RUST_LOG:-debug}"

HOST="${HOST:-10.0.0.2}"
PORT="${PORT:-4443}"
ADDR="${ADDR:-$HOST:$PORT}"
NAMESPACE="${NAMESPACE:-bbb}"

# FONTOS: namespace URL
URL="${URL:-"https://$ADDR/$NAMESPACE"}"

ENABLE_DELIVERY="${ENABLE_DELIVERY:-false}"
DEADLINE_THRESHOLD_MS="${DEADLINE_THRESHOLD_MS:-50}"

ARGS="--tls-disable-verify"

# Only add the flag if ENABLE_DELIVERY is true
if [ "$ENABLE_DELIVERY" = "true" ]; then
    ARGS="$ARGS --enable-delivery"
fi

ARGS="$ARGS --deadline-threshold-ms $DEADLINE_THRESHOLD_MS"

./target/release/moq-sub --name "$NAMESPACE" "$URL" $ARGS "$@" | ffplay -
